apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-datadog-lib
  title: Go Datadog Library
  tags:
    - "go"
    - "pkg"
  annotations:
    github.com/project-slug: coopnorge/go-datadog-lib
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/go/?tab=containers
      title: Official Datadog golang docs
      icon: web
    - url: https://docs.datadoghq.com/integrations/statsd/?tab=host
      title: Official Datadog StatsD docs
      icon: web
spec:
  type: library
  lifecycle: experimental
  owner: engineering
  dependsOn:
    - component:devtools-golang-v1beta1
    - component:github-workflow-supply-chain-security-validation
    - component:github-workflow-techdocs
    - component:go-logger
    - component:techdocs
    - component:vale-coop
