apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-datadog-lib
  annotations:
    github.com/project-slug: coopnorge/go-datadog-lib
spec:
  type: other
  lifecycle: unknown
  owner: engineering
