# Default state for all rules
default: true
# MD001/heading-increment/header-increment
# Heading levels should only increment by one level at a time
MD001: true
# MD003/heading-style/header-style - Heading style
MD003:
  # Heading style
  style: "consistent"
MD010: false
MD012:
  # Consecutive blank lines
  maximum: 1
# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 70
  # Number of characters for headings
  heading_line_length: 70
  # Number of characters for code blocks
  code_block_line_length: 120
