---
name: Project Build
on:
  push:
    branches-ignore: [ main ]

jobs:
  lint:
    name: Project Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed
          # to get a proper list of changed files
          # within `super-linter`
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          # Lint only changed files
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_MARKDOWN: true
          VALIDATE_GO: true
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: .github/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Project
        run: go build -v ./...

  build:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "Done"
