---
name: Project Test
on:
  push:
    branches-ignore: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Project Build, Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Code coverage - Test Code Base
        run: |
          go test -v -race ./... -covermode=atomic -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out

  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Done"
