---
name: Project Validation
on:
  push:
    branches-ignore: [ main ]
jobs:
  lint:
    name: Lint and Test Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed
          # to get a proper list of changed files
          # within `super-linter`
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          # Lint only changed files
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_MARKDOWN: true
          VALIDATE_GO: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: go test -v -race -p=1 ./...

      - name: Code coverage - Go Coverage Badge  # Pass the `coverage.out` output to this action
        uses: tj-actions/coverage-badge-go@v1.2
        with:
          filename: coverage.out

      - name: Code coverage - Verify Changed files
        uses: tj-actions/verify-changed-files@v9.1
        id: verify-changed-files
        with:
          files: README.md

      - name: Code coverage - Commit
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "chore: Updated coverage badge."

      - name: Code coverage - Push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.head_ref }}
  build:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "Done"
